@startuml

title __INSTAGRAM-FLUENT-API's Class Diagram__\n

  namespace tw.waterball.api {
    abstract class tw.waterball.api.AbstractInstagramId {
    }
  }
  

  namespace tw.waterball.api {
    abstract class tw.waterball.api.AbstractInstagramPk {
    }
  }
  

  namespace tw.waterball.api {
    interface tw.waterball.api.Instagram {
    }
  }
  

  namespace tw.waterball.api {
    interface tw.waterball.api.InstagramComment {
    }
  }
  

  namespace tw.waterball.api {
    interface tw.waterball.api.InstagramFeed {
    }
  }
  

  namespace tw.waterball.api {
    interface tw.waterball.api.InstagramId {
    }
  }
  

  namespace tw.waterball.api {
    interface tw.waterball.api.InstagramInbox {
    }
  }
  

  namespace tw.waterball.api {
    interface tw.waterball.api.InstagramInboxThread {
    }
  }
  

  namespace tw.waterball.api {
    interface tw.waterball.api.InstagramMediaType {
    }
  }
  

  namespace tw.waterball.api {
    interface tw.waterball.api.InstagramPendingInboxThread {
    }
  }
  

  namespace tw.waterball.api {
    interface tw.waterball.api.InstagramPk {
    }
  }
  

  namespace tw.waterball.api {
    class tw.waterball.api.InstagramProperties {
    }
  }
  

  namespace tw.waterball.api {
    interface tw.waterball.api.InstagramSession {
    }
  }
  

  namespace tw.waterball.api {
    interface tw.waterball.api.InstagramUser {
    }
  }
  

  namespace tw.waterball.api {
    namespace foreach {
      class tw.waterball.api.foreach.ForeachFeed {
      }
    }
  }
  

  namespace tw.waterball.api {
    namespace foreach {
      class tw.waterball.api.foreach.ForeachPendingThread {
      }
    }
  }
  

  namespace tw.waterball.api {
    namespace foreach {
      class tw.waterball.api.foreach.ForeachString {
      }
    }
  }
  

  namespace tw.waterball.api {
    namespace foreach {
      class tw.waterball.api.foreach.ForeachThread {
      }
    }
  }
  

  namespace tw.waterball.api {
    namespace foreach {
      class tw.waterball.api.foreach.ForeachUser {
      }
    }
  }
  

  namespace tw.waterball.api {
    namespace mocks {
      class tw.waterball.api.mocks.MockInstagram4JFeedAdapter {
      }
    }
  }
  

  namespace tw.waterball.api {
    namespace mocks {
      class tw.waterball.api.mocks.MockInstagram4JUserAdapter {
      }
    }
  }
  

  namespace tw.waterball.demo {
    class tw.waterball.demo.ApproveAllPendingInboxMessages {
    }
  }
  

  namespace tw.waterball.demo {
    class tw.waterball.demo.FollowRecentCommenters {
    }
  }
  

  namespace tw.waterball.demo {
    class tw.waterball.demo.GetAllFeeds {
    }
  }
  

  namespace tw.waterball.demo {
    class tw.waterball.demo.GetAllFollowers {
    }
  }
  

  namespace tw.waterball.demo {
    class tw.waterball.demo.GetDistinctCommenters {
    }
  }
  

  namespace tw.waterball.demo {
    class tw.waterball.demo.GetInboxThreadMessages {
    }
  }
  

  namespace tw.waterball.demo {
    class tw.waterball.demo.GetUnseenInboxMessages {
    }
  }
  

  namespace tw.waterball.demo {
    class tw.waterball.demo.InstagramStoryCrawler {
    }
  }
  

  namespace tw.waterball.exceptions {
    class tw.waterball.exceptions.InstagramException {
    }
  }
  

  namespace tw.waterball.impls.instagram4j {
    abstract class tw.waterball.impls.instagram4j.AbstractInstagram4JFeedAdapter {
    }
  }
  

  namespace tw.waterball.impls.instagram4j {
    abstract class tw.waterball.impls.instagram4j.AbstractInstagram4jUserAdapter {
    }
  }
  

  namespace tw.waterball.impls.instagram4j {
    class tw.waterball.impls.instagram4j.AdapterWrapping {
    }
  }
  

  namespace tw.waterball.impls.instagram4j {
    class tw.waterball.impls.instagram4j.Instagram4JAdapter {
    }
  }
  

  namespace tw.waterball.impls.instagram4j {
    class tw.waterball.impls.instagram4j.Instagram4JCommentAdapter {
    }
  }
  

  namespace tw.waterball.impls.instagram4j {
    class tw.waterball.impls.instagram4j.Instagram4JFeedAdapter {
    }
  }
  

  namespace tw.waterball.impls.instagram4j {
    class tw.waterball.impls.instagram4j.Instagram4JInboxAdapter {
    }
  }
  

  namespace tw.waterball.impls.instagram4j {
    class tw.waterball.impls.instagram4j.Instagram4JInboxThreadAdapter {
    }
  }
  

  namespace tw.waterball.impls.instagram4j {
    class tw.waterball.impls.instagram4j.Instagram4JInstantiator {
    }
  }
  

  namespace tw.waterball.impls.instagram4j {
    class tw.waterball.impls.instagram4j.Instagram4JPendingInboxThreadAdapter {
    }
  }
  

  namespace tw.waterball.impls.instagram4j {
    class tw.waterball.impls.instagram4j.Instagram4JSessionAdapter {
    }
  }
  

  namespace tw.waterball.impls.instagram4j {
    class tw.waterball.impls.instagram4j.Instagram4JUserAdapter {
    }
  }
  

  namespace tw.waterball.impls.instagram4j {
    class tw.waterball.impls.instagram4j.TemplateUtils {
    }
  }
  

  tw.waterball.api.AbstractInstagramId .up.|> tw.waterball.api.InstagramId
  tw.waterball.api.AbstractInstagramPk .up.|> tw.waterball.api.InstagramPk
  tw.waterball.api.foreach.ForeachPendingThread -up-|> tw.waterball.api.foreach.ForeachThread
  tw.waterball.api.mocks.MockInstagram4JFeedAdapter -up-|> tw.waterball.impls.instagram4j.AbstractInstagram4JFeedAdapter
  tw.waterball.api.mocks.MockInstagram4JUserAdapter -up-|> tw.waterball.impls.instagram4j.AbstractInstagram4jUserAdapter
  tw.waterball.impls.instagram4j.AbstractInstagram4JFeedAdapter .up.|> tw.waterball.api.InstagramFeed
  tw.waterball.impls.instagram4j.AbstractInstagram4JFeedAdapter -up-|> tw.waterball.api.AbstractInstagramPk
  tw.waterball.impls.instagram4j.AbstractInstagram4jUserAdapter .up.|> tw.waterball.api.InstagramUser
  tw.waterball.impls.instagram4j.AbstractInstagram4jUserAdapter -up-|> tw.waterball.api.AbstractInstagramPk
  tw.waterball.impls.instagram4j.AbstractInstagram4jUserAdapter o-- tw.waterball.impls.instagram4j.Instagram4JAdapter : ig
  tw.waterball.impls.instagram4j.Instagram4JAdapter .up.|> tw.waterball.api.Instagram
  tw.waterball.impls.instagram4j.Instagram4JCommentAdapter .up.|> tw.waterball.api.InstagramComment
  tw.waterball.impls.instagram4j.Instagram4JCommentAdapter -up-|> tw.waterball.api.AbstractInstagramPk
  tw.waterball.impls.instagram4j.Instagram4JCommentAdapter o-- tw.waterball.impls.instagram4j.Instagram4JAdapter : ig
  tw.waterball.impls.instagram4j.Instagram4JFeedAdapter -up-|> tw.waterball.impls.instagram4j.AbstractInstagram4JFeedAdapter
  tw.waterball.impls.instagram4j.Instagram4JFeedAdapter o-- tw.waterball.impls.instagram4j.Instagram4JAdapter : ig
  tw.waterball.impls.instagram4j.Instagram4JInboxAdapter .up.|> tw.waterball.api.InstagramInbox
  tw.waterball.impls.instagram4j.Instagram4JInboxAdapter o-- tw.waterball.impls.instagram4j.Instagram4JAdapter : ig
  tw.waterball.impls.instagram4j.Instagram4JInboxThreadAdapter .up.|> tw.waterball.api.InstagramInboxThread
  tw.waterball.impls.instagram4j.Instagram4JInboxThreadAdapter -up-|> tw.waterball.api.AbstractInstagramId
  tw.waterball.impls.instagram4j.Instagram4JInboxThreadAdapter o-- tw.waterball.impls.instagram4j.Instagram4JAdapter : ig
  tw.waterball.impls.instagram4j.Instagram4JPendingInboxThreadAdapter .up.|> tw.waterball.api.InstagramPendingInboxThread
  tw.waterball.impls.instagram4j.Instagram4JPendingInboxThreadAdapter -up-|> tw.waterball.impls.instagram4j.Instagram4JInboxThreadAdapter
  tw.waterball.impls.instagram4j.Instagram4JSessionAdapter .up.|> tw.waterball.api.InstagramSession
  tw.waterball.impls.instagram4j.Instagram4JSessionAdapter o-- tw.waterball.impls.instagram4j.Instagram4JAdapter : ig
  tw.waterball.impls.instagram4j.Instagram4JUserAdapter -up-|> tw.waterball.impls.instagram4j.AbstractInstagram4jUserAdapter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
