@startuml

title __FOREACH's Class Diagram__\n

  namespace tw.waterball.api {
    namespace foreach {
      class tw.waterball.api.foreach.ForeachFeed {
          - items : List<? extends InstagramFeed>
          + ForeachFeed()
          + aggregateCommenters()
          + aggregateComments()
          + comment()
          + filter()
          + foreach()
          + get()
          + like()
          + take()
          + unlike()
      }
    }
  }
  

  namespace tw.waterball.api {
    namespace foreach {
      class tw.waterball.api.foreach.ForeachPendingThread {
          - items : List<? extends InstagramPendingInboxThread>
          + ForeachPendingThread()
          + approve()
          + decline()
          + filter()
          + get()
      }
    }
  }
  

  namespace tw.waterball.api {
    namespace foreach {
      class tw.waterball.api.foreach.ForeachString {
          - items : List<String>
          + ForeachString()
          + filter()
          + get()
          + println()
          + take()
      }
    }
  }
  

  namespace tw.waterball.api {
    namespace foreach {
      class tw.waterball.api.foreach.ForeachThread {
          # items : List<? extends InstagramInboxThread>
          + ForeachThread()
          + filter()
          + foreach()
          + get()
          + reply()
          + take()
      }
    }
  }
  

  namespace tw.waterball.api {
    namespace foreach {
      class tw.waterball.api.foreach.ForeachUser {
          - items : List<? extends InstagramUser>
          + ForeachUser()
          + aggregateFollowers()
          + aggregateFollowings()
          + aggregateRecentFeeds()
          + aggregateRecentFollowers()
          + aggregateRecentFollowings()
          + distinct()
          + filter()
          + follow()
          + foreach()
          + get()
          + getFeeds()
          + likeRecentFeeds()
          + sendDM()
          + take()
          + unfollow()
      }
    }
  }
  

  tw.waterball.api.foreach.ForeachPendingThread -up-|> tw.waterball.api.foreach.ForeachThread


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
